# Apply Updates to Azure Local Clusters
# This workflow applies updates to clusters filtered by UpdateRing tag value
#
# AUTHENTICATION OPTIONS:
# This workflow supports two authentication methods:
# 1. OpenID Connect (OIDC) - RECOMMENDED - No secrets, uses federated credentials
# 2. Client Secret - LEGACY - Requires AZURE_CLIENT_SECRET (see commented section)
#
# For OIDC setup, see: https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect

name: Apply Updates

on:
  workflow_dispatch:
    inputs:
      update_ring:
        description: 'UpdateRing tag value to target (e.g., Wave1, Pilot, Production)'
        required: true
        default: 'Wave1'
      update_name:
        description: 'Specific update version to apply (leave empty for latest ready update)'
        required: false
        default: ''
      dry_run:
        description: 'Preview which clusters would be updated (WhatIf mode)'
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'

env:
  MODULE_PATH: './AzureLocal-Manage-Updates-Using-AUM-APIs'

jobs:
  # Optional: Add a readiness check job first
  check-readiness:
    name: Check Update Readiness
    runs-on: windows-latest
    # Required for OIDC authentication
    permissions:
      id-token: write
      contents: read
    outputs:
      ready_count: ${{ steps.readiness.outputs.READY_COUNT }}
      total_count: ${{ steps.readiness.outputs.TOTAL_COUNT }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # OPTION 1: OpenID Connect (OIDC) - RECOMMENDED
    # No client secret required - uses federated credentials
    - name: Azure CLI Login (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    # OPTION 2: Client Secret - LEGACY (uncomment if OIDC not available)
    # - name: Azure CLI Login (Client Secret)
    #   uses: azure/login@v2
    #   with:
    #     creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
    
    - name: Install Azure CLI Resource Graph Extension
      shell: pwsh
      run: |
        az extension add --name resource-graph --yes
    
    - name: Check Cluster Readiness
      shell: pwsh
      id: readiness
      run: |
        Import-Module "${{ env.MODULE_PATH }}/AzStackHci.ManageUpdates.psd1" -Force
        
        $updateRing = "${{ github.event.inputs.update_ring }}"
        
        Write-Host "Checking readiness for clusters with UpdateRing = '$updateRing'"
        
        # Create output directory
        $outputDir = "./artifacts"
        New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
        
        $csvPath = Join-Path $outputDir "readiness-report.csv"
        
        # Run readiness check
        $results = Get-AzureLocalClusterUpdateReadiness `
            -ScopeByUpdateRingTag `
            -UpdateRingValue $updateRing `
            -ExportCsvPath $csvPath
        
        $totalCount = $results.Count
        $readyCount = ($results | Where-Object { $_.ReadyForUpdate -eq $true }).Count
        
        Write-Host ""
        Write-Host "========================================" -ForegroundColor Cyan
        Write-Host "Readiness Summary" -ForegroundColor Cyan
        Write-Host "========================================" -ForegroundColor Cyan
        Write-Host "Total Clusters: $totalCount"
        Write-Host "Ready for Update: $readyCount"
        Write-Host "Not Ready: $($totalCount - $readyCount)"
        
        echo "READY_COUNT=$readyCount" >> $env:GITHUB_OUTPUT
        echo "TOTAL_COUNT=$totalCount" >> $env:GITHUB_OUTPUT
    
    - name: Upload Readiness Report
      uses: actions/upload-artifact@v4
      with:
        name: readiness-report
        path: ./artifacts/readiness-report.csv
        retention-days: 30

  # Main job to apply updates
  apply-updates:
    name: Apply Updates
    runs-on: windows-latest
    # Required for OIDC authentication
    permissions:
      id-token: write
      contents: read
    needs: check-readiness
    # Only run if there are clusters ready for update
    if: ${{ needs.check-readiness.outputs.ready_count > 0 }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # OPTION 1: OpenID Connect (OIDC) - RECOMMENDED
    - name: Azure CLI Login (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    # OPTION 2: Client Secret - LEGACY (uncomment if OIDC not available)
    # - name: Azure CLI Login (Client Secret)
    #   uses: azure/login@v2
    #   with:
    #     creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
    
    - name: Install Azure CLI Resource Graph Extension
      shell: pwsh
      run: |
        az extension add --name resource-graph --yes
    
    - name: Apply Updates
      shell: pwsh
      id: apply-updates
      run: |
        Import-Module "${{ env.MODULE_PATH }}/AzStackHci.ManageUpdates.psd1" -Force
        
        $updateRing = "${{ github.event.inputs.update_ring }}"
        $updateName = "${{ github.event.inputs.update_name }}"
        $dryRun = "${{ github.event.inputs.dry_run }}" -eq "true"
        
        # Create output directory
        $outputDir = "./artifacts"
        New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
        
        $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
        $junitPath = Join-Path $outputDir "update-results.xml"
        
        # Build parameters
        $params = @{
            ScopeByUpdateRingTag = $true
            UpdateRingValue = $updateRing
            Force = $true
            LogFolderPath = $outputDir
            ExportResultsPath = $junitPath
        }
        
        if ($updateName -and $updateName -ne '') {
            $params['UpdateName'] = $updateName
            Write-Host "Applying specific update: $updateName"
        }
        
        if ($dryRun) {
            $params['WhatIf'] = $true
            Write-Host "DRY RUN MODE - No updates will be applied"
        }
        
        Write-Host ""
        Write-Host "========================================" -ForegroundColor Cyan
        Write-Host "Applying Updates to UpdateRing: $updateRing" -ForegroundColor Cyan
        Write-Host "========================================" -ForegroundColor Cyan
        
        # Run updates
        $results = Start-AzureLocalClusterUpdate @params
        
        Write-Host ""
        Write-Host "Update operation complete"
        
        # Count results
        $succeeded = ($results | Where-Object { $_.Status -eq 'Started' -or $_.Status -eq 'Success' }).Count
        $skipped = ($results | Where-Object { $_.Status -eq 'Skipped' }).Count
        $failed = ($results | Where-Object { $_.Status -eq 'Failed' }).Count
        
        echo "SUCCEEDED=$succeeded" >> $env:GITHUB_OUTPUT
        echo "SKIPPED=$skipped" >> $env:GITHUB_OUTPUT
        echo "FAILED=$failed" >> $env:GITHUB_OUTPUT
    
    - name: Upload Update Logs
      uses: actions/upload-artifact@v4
      with:
        name: update-logs
        path: ./artifacts/*
        retention-days: 30
    
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Azure Local Update Results
        path: ./artifacts/update-results.xml
        reporter: java-junit
      continue-on-error: true
    
    - name: Summary
      shell: pwsh
      run: |
        $updateRing = "${{ github.event.inputs.update_ring }}"
        $dryRun = "${{ github.event.inputs.dry_run }}" -eq "true"
        $succeeded = "${{ steps.apply-updates.outputs.SUCCEEDED }}"
        $skipped = "${{ steps.apply-updates.outputs.SKIPPED }}"
        $failed = "${{ steps.apply-updates.outputs.FAILED }}"
        $readyCount = "${{ needs.check-readiness.outputs.ready_count }}"
        $totalCount = "${{ needs.check-readiness.outputs.total_count }}"
        
        Write-Host "## Update Application Summary" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "**Target UpdateRing:** $updateRing" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "" >> $env:GITHUB_STEP_SUMMARY
        
        if ($dryRun) {
            Write-Host "⚠️ **This was a dry run. No updates were applied.**" >> $env:GITHUB_STEP_SUMMARY
            Write-Host "" >> $env:GITHUB_STEP_SUMMARY
        }
        
        Write-Host "### Readiness" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "| Metric | Count |" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "|--------|-------|" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "| Total Clusters | $totalCount |" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "| Ready for Update | $readyCount |" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "" >> $env:GITHUB_STEP_SUMMARY
        
        Write-Host "### Results" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "| Status | Count |" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "|--------|-------|" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "| ✅ Updates Started | $succeeded |" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "| ⏭️ Skipped | $skipped |" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "| ❌ Failed | $failed |" >> $env:GITHUB_STEP_SUMMARY

  # Handle case when no clusters are ready
  no-clusters-ready:
    name: No Clusters Ready
    runs-on: windows-latest
    needs: check-readiness
    if: ${{ needs.check-readiness.outputs.ready_count == 0 }}
    
    steps:
    - name: Report No Ready Clusters
      shell: pwsh
      run: |
        $updateRing = "${{ github.event.inputs.update_ring }}"
        $totalCount = "${{ needs.check-readiness.outputs.total_count }}"
        
        Write-Host "## No Clusters Ready for Update" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "**Target UpdateRing:** $updateRing" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "" >> $env:GITHUB_STEP_SUMMARY
        
        if ($totalCount -eq 0) {
            Write-Host "⚠️ No clusters found with UpdateRing tag value '$updateRing'" >> $env:GITHUB_STEP_SUMMARY
        } else {
            Write-Host "⚠️ Found $totalCount cluster(s) with UpdateRing='$updateRing', but none are ready for updates." >> $env:GITHUB_STEP_SUMMARY
            Write-Host "" >> $env:GITHUB_STEP_SUMMARY
            Write-Host "Possible reasons:" >> $env:GITHUB_STEP_SUMMARY
            Write-Host "- Clusters may already be up to date" >> $env:GITHUB_STEP_SUMMARY
            Write-Host "- Updates may be in progress" >> $env:GITHUB_STEP_SUMMARY
            Write-Host "- Clusters may have health check failures" >> $env:GITHUB_STEP_SUMMARY
            Write-Host "" >> $env:GITHUB_STEP_SUMMARY
            Write-Host "Download the readiness report artifact for details." >> $env:GITHUB_STEP_SUMMARY
        }
        
        Write-Warning "No clusters ready for update in ring '$updateRing'"
